project:
  type: website
  output-dir: docs

website:
  title: "The Kids Biostats"
  favicon: thekids_logo.png
  site-url: "https://www.the-kids-biostats.github.io"
  description: "Biostats R solutions"
  navbar:
    logo: thekids_logo.png
    pinned: TRUE
    right:
      - about.qmd
      - icon: github
        href: https://github.com/The-Kids-Biostats/The-Kids-Biostats.github.io
      - icon: rss
        href: index.xml
      - icon: twitter
        href: "https://x.com/telethonkids"
      - text: "R-bloggers"
        href: https://www.r-bloggers.com
format:
  html:
    theme: cosmo
    css: styles.css
    embed-resources: true

editor: visual

