project:
  type: website
  output-dir: docs

website:
  title: "The Kids Biostats"
  site-url: "https://www.the-kids-biostats.github.io"
  description: "Biostats R solutions"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/The-Kids-Biostats/The-Kids-Biostats.github.io
      - icon: rss
        href: index.xml
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

