project:
  type: website
  output-dir: docs

website:
  title: "The Kids Biostats"
  site-url: "https://www.the-kids-biostats.github.io"
  description: "Biostats R solutions"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

