project:
  type: website
  output-dir: docs

website:
  title: "The Kids Biostats"
  favicon: thekids_logo.png
  site-url: "https://the-kids-biostats.github.io"
  description: "Biostats R solutions"
  navbar:
    logo: thekids_logo.png
    pinned: TRUE
    right:
      - about.qmd
      - icon: github
        href: https://github.com/The-Kids-Biostats/The-Kids-Biostats.github.io
      - icon: rss
        href: index.xml
      - icon: twitter
        href: "https://x.com/telethonkids"
      - text: "Our Package"
        href: https://github.com/The-Kids-Biostats/thekidsbiostats
      - text: "Model Guides"
        href: https://the-kids-biostats.github.io/model_guides/
format:
  html:
    theme: cosmo
    css: styles.css
    callout-icon: false

editor: visual

