---
title: "AI in Biostatistics - Part 2"
output: html_document
date: "2024-05-06"
author: "Dr Matthew Cooper, Wesley Billingham"
categories:
  - AI
  - R
draft: true
---

# Overview

If you haven't read part one of this two-part series on AI, do that first here:

Last time we looked at three cases where our use of AI aided our productivity and gave us the desired result. In this post, we'll be looking at the other side of the coin to situations where AI has struggled and attempts to use it in these situations would hinder our productivity and potentially give us incorrect output. 

To demonstrate this point, we'll look through the results of a few published papers and some concepts they introduce. Then we will examine some guidelines we can use to maximise our efficiency by using AI appropriately. 

## Format of this post

# Examples

## Example 1 - Jagged Frontier



## Example 2 - Biostatistical Questions



## Bonus Example - Endodontics

# Discussion

## Results from Jagged Frontier Paper

## Brief Review of Part One

## Where to from here?/Our Recommendations

# Conclusion