{
  "hash": "82feb43b2d8b58fc3b89f1d02c235653",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Summary Tabling in R\"\nauthor: \"Zac Dempsey\"\nformat:\n  html:\n    code-fold: true\n    toc: true\n    toc-location: left\ndate: \"2024-07-01\"\ncategories:\n  - R\n  - Summary\ndraft: true\n---\n\n\n\n\n# Overview\n\nAnalysing data will normally always involve generating tables– whether they are the final goal of the analysis or used as an intermediary step to guide further analysis. This blog post will focus on the former, while keeping the latter in the back of our minds. A common use case here might be a \"Table 1\" from a randomised control trial where we are examining (not testing and generating p-values) a range of summary statistics for each arm of the trial, or perhaps data are collected on a group over three time points and we want to examine a range of summary statistics for each time point.\n\nThere are *many* `R` packages and functions dedicated to this very task. We will select just a handful that we often come across in our work, and evaluate their effectiveness relative to some pre-set criteria we deem important in our work. Example code and commentary will be presented as we go.\n\n<br>\n\n# Assessment Criteria\n\n1.  **Range of customisible summary options**\n\n    -   How flexible are the summary functions to different metrics (mean, median, SD, IQR)?\n\n    -   How easy is it to apply these changes to different data types (e.g., continuous, dichotomous, ordinal, nominal).\n\n2.  **Flexibility in changing tabling output**\n\n    -   Text formatting (italics, bolding, font size, etc.)\n\n    -   Specifying order for table elements\n\n    -   Rounding\n\n3.  **Rendering across different output types**\n\n    -   Are the outputs robust with respect to output form (html, pdf, word)?\n\n<br>\n\n# Contenders\n\nLet's define our set of contenting packages. Keep in mind this is not an exhaustive list of all summary and tabling functions – we select only a few that we often use or come across in our work. Any function is considered that is capable of presenting a formatted summary table in html, pdf and/or Word form. Therefore, the various summary tabling functions that print output to console (e.g., `Hmisc::describe`, `tableone::CreateTableOne`) are not considered.\n\n-   [`gtsummary::tbl_summary`](https://www.danieldsjoberg.com/gtsummary/)\n-   [`table1::table1`](https://cran.r-project.org/web/packages/table1/vignettes/table1-examples.html)\n-   [`desctable::desc_table`](https://cran.r-project.org/web/packages/desctable/vignettes/desctable.html)\n-   [`summarytools::dfSummary`](https://rdrr.io/cran/summarytools/man/dfSummary.html)\n-   [`janitor::tabyl`](https://cran.r-project.org/web/packages/janitor/vignettes/tabyls.html)\n-   [`stargazer::stargazer`](https://cran.r-project.org/web/packages/stargazer/vignettes/stargazer.pdf)\n-   tableone\n-   [custom](https://mcfromnz.wordpress.com/2010/09/21/automatic-descriptive-statistic-tables/)\n\n<br>\n\n# Data\n\n## Sample Dataset\n\nTo evaluate the summary table functions, we select a data set and make a few minor changes to ensure it has the right variety of variables types to test all of our required scenarios.\n\nWe will use the `flchain` (Assay of serum free light chain for 7874 subjects) dataset from the `survival` package.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(flchain, package = \"survival\")\n\nhead(flchain)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  age sex sample.yr kappa lambda flc.grp creatinine mgus futime death\n1  97   F      1997  5.70  4.860      10        1.7    0     85     1\n2  92   F      2000  0.87  0.683       1        0.9    0   1281     1\n3  94   F      1997  4.36  3.850      10        1.4    0     69     1\n4  92   F      1996  2.42  2.220       9        1.0    0    115     1\n5  93   F      1996  1.32  1.690       6        1.1    0   1039     1\n6  90   F      1997  2.01  1.860       9        1.0    0   1355     1\n      chapter\n1 Circulatory\n2   Neoplasms\n3 Circulatory\n4 Circulatory\n5 Circulatory\n6      Mental\n```\n\n\n:::\n\n```{.r .cell-code}\nstr(flchain)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n'data.frame':\t7874 obs. of  11 variables:\n $ age       : num  97 92 94 92 93 90 90 90 93 91 ...\n $ sex       : Factor w/ 2 levels \"F\",\"M\": 1 1 1 1 1 1 1 1 1 1 ...\n $ sample.yr : num  1997 2000 1997 1996 1996 ...\n $ kappa     : num  5.7 0.87 4.36 2.42 1.32 2.01 0.43 2.47 1.91 0.791 ...\n $ lambda    : num  4.86 0.683 3.85 2.22 1.69 1.86 0.88 2.7 2.18 2.22 ...\n $ flc.grp   : num  10 1 10 9 6 9 1 10 9 6 ...\n $ creatinine: num  1.7 0.9 1.4 1 1.1 1 0.8 1.2 1.2 0.8 ...\n $ mgus      : num  0 0 0 0 0 0 0 0 0 0 ...\n $ futime    : int  85 1281 69 115 1039 1355 2851 372 3309 1326 ...\n $ death     : num  1 1 1 1 1 1 1 1 1 1 ...\n $ chapter   : Factor w/ 16 levels \"Blood\",\"Circulatory\",..: 2 13 2 2 2 11 11 14 15 2 ...\n```\n\n\n:::\n:::\n\n\nThis has the following variable types\n\n-   Continuous (numeric)\n\n    -   `age`\n\n    -   `kappa`\n\n    -   `lambda`\n\n    -   `futime`\n\n    -   `creatinine`\n\n-   Ordinal\n\n    -   `sample.yr`\n\n    -   `death`\n\n    -   `chapter`\n\n-   Nominal\n\n    -   `sex`\n\n    -   `mgus`\n\n    -   `flc.grp`\n\n<p>\n\n## Objectives\n\nFor each method, we will:\n\n-   Report median (interquartile range) for `age` and mean (standard deviation) for all other continuous (numeric) variables.\n-   Apply level specifications to ordinal variables (`sample.yr`)\n-   Stratify results by `death`.\n-   Report the `lambda` statistics to 1 decimal place.\n-   Rename sample.yr to Sample Year.\n-   Render in html, pdf and word and compare consistency across these.\n\nWhere any of the above was seemingly not possible, it will be reported in the comments of that method. Comments will also be made on the quality of the documentation for each package and the wealth of online support through StackOverflow, blogs, tutorials, etc.\n\n# Summary Tables\n\n## Method 1 - `gtsummary`\n\n-   Required data structure:\n    -   In general, `tbl_summary` requires data in **long format**. This is consistent across both the `tbl_summary` and `tbl_strata` functions.\n    -   \"Columns\" in the output are defined by use of the `by =` argument.\n    -   \"Rows\" in the output are defined by columns in the input data set.\n    -   All variables included in the input data are, by default, included in the output. Therefore, the user must select/un-select columns pursuant to what is required.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#tf <- tempfile(\"example\", fileext = \".docx\")\n\nflchain %>%\n  gtsummary::tbl_summary(by = \"death\", # Levels to separate data by\n                         missing = \"ifany\", # Show missing values for a variable only if they exist\n                         digits = list(all_categorical() ~ c(0, 2), # Categorical counts 0dp; relative percentage 2dp\n                                       all_continuous() ~ 2, # Continuous summary stats 2dp\n                                       lambda ~ 1), # Report stats for `lambda` to 1dp\n                         type = all_continuous() ~ \"continuous2\", # Define multi-level summary stats for all continuous variables\n                         statistic = list(all_continuous() ~ c(\"{mean} ({sd})\",            # Display mean & standard deviation\n                                                               \"{median} ({p25}, {p75})\"), # Display median & IQR\n                                          all_categorical() ~ \"{n} ({p}%)\"),               # Display count & percentage\n                         label = list(sample.yr ~ \"Sample Year\")) %>% # Amend label of `sample.yr`\n  \n  add_overall(last = TRUE) %>% # Add overall counts, set to `last` column of output\n  italicize_labels() %>% # Italicize variable labels\n  \n  add_p(test = list(all_categorical() ~ \"chisq.test\", # Apply chi square test to all categorical variables\n                    c(kappa, lambda) ~ \"t.test\", # Apply t.test to `kappa`, `lambda`\n                    c(flc.grp, creatinine) ~ \"kruskal.test\"), # Apply Kruskal-Wallis test to `flc.grp` and `creatinine`\n        test.args = list(all_tests(\"t.test\") ~ list(var.equal = F, # Equal variance assumption for t-test FALSE\n                                                       paired = F), # Paired t-test FALSE\n                         all_tests(\"chisq.test\") ~ list(correct = F)), # Continuity correction = FALSE to chi-square test                                                   \n        pvalue_fun = function(x) style_pvalue(x, digits = 3)) # Set p-value rounding (`gtsummary::style_pvalue` supports only values 1, 2, 3)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following errors were returned during `add_p()`:\n✖ For variable `age` (`death`) and \"p.value\" statistic: The package \"cardx\" (>=\n  0.2.0) is required.\n✖ For variable `chapter` (`death`) and \"p.value\" statistic: The package \"cardx\"\n  (>= 0.2.0) is required.\n✖ For variable `creatinine` (`death`) and \"p.value\" statistic: The package\n  \"cardx\" (>= 0.2.0) is required.\n✖ For variable `flc.grp` (`death`) and \"p.value\" statistic: The package \"cardx\"\n  (>= 0.2.0) is required.\n✖ For variable `futime` (`death`) and \"p.value\" statistic: The package \"cardx\"\n  (>= 0.2.0) is required.\n✖ For variable `kappa` (`death`) and \"p.value\" statistic: The package \"cardx\"\n  (>= 0.2.0) is required.\n✖ For variable `lambda` (`death`) and \"p.value\" statistic: The package \"cardx\"\n  (>= 0.2.0) is required.\n✖ For variable `mgus` (`death`) and \"p.value\" statistic: The package \"cardx\"\n  (>= 0.2.0) is required.\n✖ For variable `sample.yr` (`death`) and \"p.value\" statistic: The package\n  \"cardx\" (>= 0.2.0) is required.\n✖ For variable `sex` (`death`) and \"p.value\" statistic: The package \"cardx\" (>=\n  0.2.0) is required.\n```\n\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"towcynycze\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#towcynycze table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#towcynycze thead, #towcynycze tbody, #towcynycze tfoot, #towcynycze tr, #towcynycze td, #towcynycze th {\n  border-style: none;\n}\n\n#towcynycze p {\n  margin: 0;\n  padding: 0;\n}\n\n#towcynycze .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#towcynycze .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#towcynycze .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#towcynycze .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#towcynycze .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#towcynycze .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#towcynycze .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#towcynycze .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#towcynycze .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#towcynycze .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#towcynycze .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#towcynycze .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#towcynycze .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#towcynycze .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#towcynycze .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#towcynycze .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#towcynycze .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#towcynycze .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#towcynycze .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#towcynycze .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#towcynycze .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#towcynycze .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#towcynycze .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#towcynycze .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#towcynycze .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#towcynycze .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#towcynycze .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#towcynycze .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#towcynycze .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#towcynycze .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#towcynycze .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#towcynycze .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#towcynycze .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#towcynycze .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#towcynycze .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#towcynycze .gt_left {\n  text-align: left;\n}\n\n#towcynycze .gt_center {\n  text-align: center;\n}\n\n#towcynycze .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#towcynycze .gt_font_normal {\n  font-weight: normal;\n}\n\n#towcynycze .gt_font_bold {\n  font-weight: bold;\n}\n\n#towcynycze .gt_font_italic {\n  font-style: italic;\n}\n\n#towcynycze .gt_super {\n  font-size: 65%;\n}\n\n#towcynycze .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#towcynycze .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#towcynycze .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#towcynycze .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#towcynycze .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#towcynycze .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#towcynycze .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#towcynycze .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#towcynycze div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;div data-qmd-base64=&quot;KipDaGFyYWN0ZXJpc3RpYyoq&quot;&gt;&lt;div class='gt_from_md'&gt;&lt;p&gt;&lt;strong&gt;Characteristic&lt;/strong&gt;&lt;/p&gt;&#10;&lt;/div&gt;&lt;/div&gt;\"><div data-qmd-base64=\"KipDaGFyYWN0ZXJpc3RpYyoq\"><div class='gt_from_md'><p><strong>Characteristic</strong></p>\n</div></div></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;div data-qmd-base64=&quot;KiowKiogIApOID0gNSw3MDU=&quot;&gt;&lt;div class='gt_from_md'&gt;&lt;p&gt;&lt;strong&gt;0&lt;/strong&gt;&lt;br /&gt;&#10;N = 5,705&lt;/p&gt;&#10;&lt;/div&gt;&lt;/div&gt;&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;line-height: 0;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><div data-qmd-base64=\"KiowKiogIApOID0gNSw3MDU=\"><div class='gt_from_md'><p><strong>0</strong><br />\nN = 5,705</p>\n</div></div><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height: 0;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;div data-qmd-base64=&quot;KioxKiogIApOID0gMiwxNjk=&quot;&gt;&lt;div class='gt_from_md'&gt;&lt;p&gt;&lt;strong&gt;1&lt;/strong&gt;&lt;br /&gt;&#10;N = 2,169&lt;/p&gt;&#10;&lt;/div&gt;&lt;/div&gt;&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;line-height: 0;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><div data-qmd-base64=\"KioxKiogIApOID0gMiwxNjk=\"><div class='gt_from_md'><p><strong>1</strong><br />\nN = 2,169</p>\n</div></div><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height: 0;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;div data-qmd-base64=&quot;KipPdmVyYWxsKiogIApOID0gNyw4NzQ=&quot;&gt;&lt;div class='gt_from_md'&gt;&lt;p&gt;&lt;strong&gt;Overall&lt;/strong&gt;&lt;br /&gt;&#10;N = 7,874&lt;/p&gt;&#10;&lt;/div&gt;&lt;/div&gt;&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;line-height: 0;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><div data-qmd-base64=\"KipPdmVyYWxsKiogIApOID0gNyw4NzQ=\"><div class='gt_from_md'><p><strong>Overall</strong><br />\nN = 7,874</p>\n</div></div><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height: 0;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;div data-qmd-base64=&quot;KipwLXZhbHVlKio=&quot;&gt;&lt;div class='gt_from_md'&gt;&lt;p&gt;&lt;strong&gt;p-value&lt;/strong&gt;&lt;/p&gt;&#10;&lt;/div&gt;&lt;/div&gt;\"><div data-qmd-base64=\"KipwLXZhbHVlKio=\"><div class='gt_from_md'><p><strong>p-value</strong></p>\n</div></div></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-style: italic;\">age</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Mean (SD)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">60.84 (8.20)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">73.39 (10.32)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">64.29 (10.46)</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Median (Q1, Q3)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">59.00 (54.00, 66.00)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">74.00 (67.00, 81.00)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">63.00 (55.00, 72.00)</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-style: italic;\">sex</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    F</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">3,185 (55.83%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">1,165 (53.71%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">4,350 (55.25%)</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    M</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">2,520 (44.17%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">1,004 (46.29%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">3,524 (44.75%)</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-style: italic;\">Sample Year</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    1995</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">861 (15.09%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">414 (19.09%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">1,275 (16.19%)</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    1996</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">2,435 (42.68%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">1,056 (48.69%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">3,491 (44.34%)</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    1997</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">1,012 (17.74%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">369 (17.01%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">1,381 (17.54%)</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    1998</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">526 (9.220%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">161 (7.423%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">687 (8.725%)</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    1999</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">283 (4.961%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">67 (3.089%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">350 (4.445%)</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    2000</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">193 (3.383%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">52 (2.397%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">245 (3.112%)</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    2001</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">137 (2.401%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">38 (1.752%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">175 (2.223%)</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    2002</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">47 (0.824%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">1 (0.046%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">48 (0.610%)</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    2003</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">211 (3.699%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">11 (0.507%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">222 (2.819%)</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-style: italic;\">kappa</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Mean (SD)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">1.27 (0.65)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">1.85 (1.26)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">1.43 (0.90)</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Median (Q1, Q3)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">1.19 (0.91, 1.53)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">1.57 (1.16, 2.14)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">1.27 (0.96, 1.68)</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-style: italic;\">lambda</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Mean (SD)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">1.5 (0.7)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">2.1 (1.5)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">1.7 (1.0)</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Median (Q1, Q3)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">1.4 (1.2, 1.8)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">1.8 (1.4, 2.4)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">1.5 (1.2, 1.9)</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-style: italic;\">flc.grp</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Mean (SD)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">4.98 (2.72)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">6.77 (2.84)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">5.47 (2.86)</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Median (Q1, Q3)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">5.00 (3.00, 7.00)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">7.00 (5.00, 9.00)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">5.00 (3.00, 8.00)</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-style: italic;\">creatinine</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Mean (SD)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">1.05 (0.31)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">1.19 (0.59)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">1.09 (0.42)</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Median (Q1, Q3)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">1.00 (0.90, 1.20)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">1.10 (0.90, 1.30)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">1.00 (0.90, 1.20)</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Unknown</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">1,143</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">207</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">1,350</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-style: italic;\">mgus</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">99 (1.735%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">16 (0.738%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">115 (1.461%)</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-style: italic;\">futime</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Mean (SD)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">4,226.20 (974.25)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">2,174.54 (1,380.34)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">3,661.04 (1,432.68)</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Median (Q1, Q3)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">4,607.00 (4,033.00, 4,852.00)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">2,165.00 (945.00, 3,282.00)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">4,302.00 (2,852.00, 4,773.00)</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-style: italic;\">chapter</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Blood</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">0 (NA%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">4 (0.184%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">4 (0.184%)</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Circulatory</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">0 (NA%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">745 (34.35%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">745 (34.35%)</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Congenital</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">0 (NA%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">3 (0.138%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">3 (0.138%)</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Digestive</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">0 (NA%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">66 (3.043%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">66 (3.043%)</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Endocrine</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">0 (NA%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">48 (2.213%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">48 (2.213%)</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    External Causes</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">0 (NA%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">66 (3.043%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">66 (3.043%)</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Genitourinary</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">0 (NA%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">42 (1.936%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">42 (1.936%)</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Ill Defined</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">0 (NA%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">38 (1.752%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">38 (1.752%)</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Infectious</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">0 (NA%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">32 (1.475%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">32 (1.475%)</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Injury and Poisoning</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">0 (NA%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">21 (0.968%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">21 (0.968%)</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Mental</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">0 (NA%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">144 (6.639%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">144 (6.639%)</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Musculoskeletal</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">0 (NA%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">14 (0.645%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">14 (0.645%)</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Neoplasms</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">0 (NA%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">567 (26.14%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">567 (26.14%)</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Nervous</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">0 (NA%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">130 (5.994%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">130 (5.994%)</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Respiratory</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">0 (NA%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">245 (11.30%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">245 (11.30%)</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Skin</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">0 (NA%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">4 (0.184%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">4 (0.184%)</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Unknown</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">5,705</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">0</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">5,705</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n  </tbody>\n  \n  <tfoot class=\"gt_footnotes\">\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"5\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height: 0;\"><sup>1</sup></span> <div data-qmd-base64=\"biAoJSk=\"><div class='gt_from_md'><p>n (%)</p>\n</div></div></td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n\n```{.r .cell-code}\n  #as_gt() %>% \n  #gt::gtsave(filename = \"example.docx\")\n```\n:::\n\n\n<p>\n\n-   For stratified tables, we can use `tbl_summary` inside of the `tbl_strata` function. Take for example the below, which stratifies by `sex`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nflchain %>%\n  tbl_strata(strata = sex, \n             .tbl_fun = ~.x %>%\n  gtsummary::tbl_summary(by = \"death\",\n                         # test 1\n                         digits = lambda ~ 1,\n                         label = sample.yr ~ \"Sample Year\") %>%\n  add_overall(last = TRUE) %>%\n  italicize_labels() %>%\n  add_p())\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following errors were returned during `tbl_strata()`:\n✖ For variable `age` (`death`) and \"p.value\" statistic: The package \"cardx\" (>=\n  0.2.0) is required.\n✖ For variable `chapter` (`death`) and \"p.value\" statistic: The package \"cardx\"\n  (>= 0.2.0) is required.\n✖ For variable `creatinine` (`death`) and \"p.value\" statistic: The package\n  \"cardx\" (>= 0.2.0) is required.\n✖ For variable `flc.grp` (`death`) and \"p.value\" statistic: The package \"cardx\"\n  (>= 0.2.0) is required.\n✖ For variable `futime` (`death`) and \"p.value\" statistic: The package \"cardx\"\n  (>= 0.2.0) is required.\n✖ For variable `kappa` (`death`) and \"p.value\" statistic: The package \"cardx\"\n  (>= 0.2.0) is required.\n✖ For variable `lambda` (`death`) and \"p.value\" statistic: The package \"cardx\"\n  (>= 0.2.0) is required.\n✖ For variable `mgus` (`death`) and \"p.value\" statistic: The package \"cardx\"\n  (>= 0.2.0) is required.\n✖ For variable `sample.yr` (`death`) and \"p.value\" statistic: The package\n  \"cardx\" (>= 0.2.0) is required.\nThe following errors were returned during `tbl_strata()`:\n✖ For variable `age` (`death`) and \"p.value\" statistic: The package \"cardx\" (>=\n  0.2.0) is required.\n✖ For variable `chapter` (`death`) and \"p.value\" statistic: The package \"cardx\"\n  (>= 0.2.0) is required.\n✖ For variable `creatinine` (`death`) and \"p.value\" statistic: The package\n  \"cardx\" (>= 0.2.0) is required.\n✖ For variable `flc.grp` (`death`) and \"p.value\" statistic: The package \"cardx\"\n  (>= 0.2.0) is required.\n✖ For variable `futime` (`death`) and \"p.value\" statistic: The package \"cardx\"\n  (>= 0.2.0) is required.\n✖ For variable `kappa` (`death`) and \"p.value\" statistic: The package \"cardx\"\n  (>= 0.2.0) is required.\n✖ For variable `lambda` (`death`) and \"p.value\" statistic: The package \"cardx\"\n  (>= 0.2.0) is required.\n✖ For variable `mgus` (`death`) and \"p.value\" statistic: The package \"cardx\"\n  (>= 0.2.0) is required.\n✖ For variable `sample.yr` (`death`) and \"p.value\" statistic: The package\n  \"cardx\" (>= 0.2.0) is required.\n```\n\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"dhaibemvqc\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#dhaibemvqc table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#dhaibemvqc thead, #dhaibemvqc tbody, #dhaibemvqc tfoot, #dhaibemvqc tr, #dhaibemvqc td, #dhaibemvqc th {\n  border-style: none;\n}\n\n#dhaibemvqc p {\n  margin: 0;\n  padding: 0;\n}\n\n#dhaibemvqc .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#dhaibemvqc .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#dhaibemvqc .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#dhaibemvqc .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#dhaibemvqc .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#dhaibemvqc .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#dhaibemvqc .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#dhaibemvqc .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#dhaibemvqc .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#dhaibemvqc .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#dhaibemvqc .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#dhaibemvqc .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#dhaibemvqc .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#dhaibemvqc .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#dhaibemvqc .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#dhaibemvqc .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#dhaibemvqc .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#dhaibemvqc .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#dhaibemvqc .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dhaibemvqc .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#dhaibemvqc .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#dhaibemvqc .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#dhaibemvqc .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dhaibemvqc .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#dhaibemvqc .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#dhaibemvqc .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#dhaibemvqc .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dhaibemvqc .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#dhaibemvqc .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#dhaibemvqc .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#dhaibemvqc .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#dhaibemvqc .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#dhaibemvqc .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dhaibemvqc .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#dhaibemvqc .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dhaibemvqc .gt_left {\n  text-align: left;\n}\n\n#dhaibemvqc .gt_center {\n  text-align: center;\n}\n\n#dhaibemvqc .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#dhaibemvqc .gt_font_normal {\n  font-weight: normal;\n}\n\n#dhaibemvqc .gt_font_bold {\n  font-weight: bold;\n}\n\n#dhaibemvqc .gt_font_italic {\n  font-style: italic;\n}\n\n#dhaibemvqc .gt_super {\n  font-size: 65%;\n}\n\n#dhaibemvqc .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#dhaibemvqc .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#dhaibemvqc .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#dhaibemvqc .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#dhaibemvqc .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#dhaibemvqc .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#dhaibemvqc .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#dhaibemvqc .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#dhaibemvqc div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings gt_spanner_row\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"2\" colspan=\"1\" scope=\"col\" id=\"&lt;div data-qmd-base64=&quot;KipDaGFyYWN0ZXJpc3RpYyoq&quot;&gt;&lt;div class='gt_from_md'&gt;&lt;p&gt;&lt;strong&gt;Characteristic&lt;/strong&gt;&lt;/p&gt;&#10;&lt;/div&gt;&lt;/div&gt;\"><div data-qmd-base64=\"KipDaGFyYWN0ZXJpc3RpYyoq\"><div class='gt_from_md'><p><strong>Characteristic</strong></p>\n</div></div></th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"4\" scope=\"colgroup\" id=\"&lt;div data-qmd-base64=&quot;KipGKio=&quot;&gt;&lt;div class='gt_from_md'&gt;&lt;p&gt;&lt;strong&gt;F&lt;/strong&gt;&lt;/p&gt;&#10;&lt;/div&gt;&lt;/div&gt;\">\n        <span class=\"gt_column_spanner\"><div data-qmd-base64=\"KipGKio=\"><div class='gt_from_md'><p><strong>F</strong></p>\n</div></div></span>\n      </th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"4\" scope=\"colgroup\" id=\"&lt;div data-qmd-base64=&quot;KipNKio=&quot;&gt;&lt;div class='gt_from_md'&gt;&lt;p&gt;&lt;strong&gt;M&lt;/strong&gt;&lt;/p&gt;&#10;&lt;/div&gt;&lt;/div&gt;\">\n        <span class=\"gt_column_spanner\"><div data-qmd-base64=\"KipNKio=\"><div class='gt_from_md'><p><strong>M</strong></p>\n</div></div></span>\n      </th>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;div data-qmd-base64=&quot;KiowKiogIApOID0gMywxODU=&quot;&gt;&lt;div class='gt_from_md'&gt;&lt;p&gt;&lt;strong&gt;0&lt;/strong&gt;&lt;br /&gt;&#10;N = 3,185&lt;/p&gt;&#10;&lt;/div&gt;&lt;/div&gt;&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;line-height: 0;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><div data-qmd-base64=\"KiowKiogIApOID0gMywxODU=\"><div class='gt_from_md'><p><strong>0</strong><br />\nN = 3,185</p>\n</div></div><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height: 0;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;div data-qmd-base64=&quot;KioxKiogIApOID0gMSwxNjU=&quot;&gt;&lt;div class='gt_from_md'&gt;&lt;p&gt;&lt;strong&gt;1&lt;/strong&gt;&lt;br /&gt;&#10;N = 1,165&lt;/p&gt;&#10;&lt;/div&gt;&lt;/div&gt;&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;line-height: 0;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><div data-qmd-base64=\"KioxKiogIApOID0gMSwxNjU=\"><div class='gt_from_md'><p><strong>1</strong><br />\nN = 1,165</p>\n</div></div><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height: 0;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;div data-qmd-base64=&quot;KipPdmVyYWxsKiogIApOID0gNCwzNTA=&quot;&gt;&lt;div class='gt_from_md'&gt;&lt;p&gt;&lt;strong&gt;Overall&lt;/strong&gt;&lt;br /&gt;&#10;N = 4,350&lt;/p&gt;&#10;&lt;/div&gt;&lt;/div&gt;&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;line-height: 0;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><div data-qmd-base64=\"KipPdmVyYWxsKiogIApOID0gNCwzNTA=\"><div class='gt_from_md'><p><strong>Overall</strong><br />\nN = 4,350</p>\n</div></div><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height: 0;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;div data-qmd-base64=&quot;KipwLXZhbHVlKio=&quot;&gt;&lt;div class='gt_from_md'&gt;&lt;p&gt;&lt;strong&gt;p-value&lt;/strong&gt;&lt;/p&gt;&#10;&lt;/div&gt;&lt;/div&gt;\"><div data-qmd-base64=\"KipwLXZhbHVlKio=\"><div class='gt_from_md'><p><strong>p-value</strong></p>\n</div></div></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;div data-qmd-base64=&quot;KiowKiogIApOID0gMiw1MjA=&quot;&gt;&lt;div class='gt_from_md'&gt;&lt;p&gt;&lt;strong&gt;0&lt;/strong&gt;&lt;br /&gt;&#10;N = 2,520&lt;/p&gt;&#10;&lt;/div&gt;&lt;/div&gt;&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;line-height: 0;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><div data-qmd-base64=\"KiowKiogIApOID0gMiw1MjA=\"><div class='gt_from_md'><p><strong>0</strong><br />\nN = 2,520</p>\n</div></div><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height: 0;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;div data-qmd-base64=&quot;KioxKiogIApOID0gMSwwMDQ=&quot;&gt;&lt;div class='gt_from_md'&gt;&lt;p&gt;&lt;strong&gt;1&lt;/strong&gt;&lt;br /&gt;&#10;N = 1,004&lt;/p&gt;&#10;&lt;/div&gt;&lt;/div&gt;&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;line-height: 0;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><div data-qmd-base64=\"KioxKiogIApOID0gMSwwMDQ=\"><div class='gt_from_md'><p><strong>1</strong><br />\nN = 1,004</p>\n</div></div><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height: 0;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;div data-qmd-base64=&quot;KipPdmVyYWxsKiogIApOID0gMyw1MjQ=&quot;&gt;&lt;div class='gt_from_md'&gt;&lt;p&gt;&lt;strong&gt;Overall&lt;/strong&gt;&lt;br /&gt;&#10;N = 3,524&lt;/p&gt;&#10;&lt;/div&gt;&lt;/div&gt;&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;line-height: 0;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><div data-qmd-base64=\"KipPdmVyYWxsKiogIApOID0gMyw1MjQ=\"><div class='gt_from_md'><p><strong>Overall</strong><br />\nN = 3,524</p>\n</div></div><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height: 0;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;div data-qmd-base64=&quot;KipwLXZhbHVlKio=&quot;&gt;&lt;div class='gt_from_md'&gt;&lt;p&gt;&lt;strong&gt;p-value&lt;/strong&gt;&lt;/p&gt;&#10;&lt;/div&gt;&lt;/div&gt;\"><div data-qmd-base64=\"KipwLXZhbHVlKio=\"><div class='gt_from_md'><p><strong>p-value</strong></p>\n</div></div></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-style: italic;\">age</td>\n<td headers=\"stat_1_1\" class=\"gt_row gt_center\">60 (54, 68)</td>\n<td headers=\"stat_2_1\" class=\"gt_row gt_center\">77 (69, 83)</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">64 (56, 73)</td>\n<td headers=\"p.value_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_1_2\" class=\"gt_row gt_center\">59 (54, 65)</td>\n<td headers=\"stat_2_2\" class=\"gt_row gt_center\">72 (65, 78)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">62 (55, 70)</td>\n<td headers=\"p.value_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-style: italic;\">Sample Year</td>\n<td headers=\"stat_1_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_1_2\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2_2\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    1995</td>\n<td headers=\"stat_1_1\" class=\"gt_row gt_center\">508 (16%)</td>\n<td headers=\"stat_2_1\" class=\"gt_row gt_center\">196 (17%)</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">704 (16%)</td>\n<td headers=\"p.value_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_1_2\" class=\"gt_row gt_center\">353 (14%)</td>\n<td headers=\"stat_2_2\" class=\"gt_row gt_center\">218 (22%)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">571 (16%)</td>\n<td headers=\"p.value_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    1996</td>\n<td headers=\"stat_1_1\" class=\"gt_row gt_center\">1,399 (44%)</td>\n<td headers=\"stat_2_1\" class=\"gt_row gt_center\">569 (49%)</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">1,968 (45%)</td>\n<td headers=\"p.value_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_1_2\" class=\"gt_row gt_center\">1,036 (41%)</td>\n<td headers=\"stat_2_2\" class=\"gt_row gt_center\">487 (49%)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">1,523 (43%)</td>\n<td headers=\"p.value_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    1997</td>\n<td headers=\"stat_1_1\" class=\"gt_row gt_center\">563 (18%)</td>\n<td headers=\"stat_2_1\" class=\"gt_row gt_center\">228 (20%)</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">791 (18%)</td>\n<td headers=\"p.value_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_1_2\" class=\"gt_row gt_center\">449 (18%)</td>\n<td headers=\"stat_2_2\" class=\"gt_row gt_center\">141 (14%)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">590 (17%)</td>\n<td headers=\"p.value_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    1998</td>\n<td headers=\"stat_1_1\" class=\"gt_row gt_center\">281 (8.8%)</td>\n<td headers=\"stat_2_1\" class=\"gt_row gt_center\">88 (7.6%)</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">369 (8.5%)</td>\n<td headers=\"p.value_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_1_2\" class=\"gt_row gt_center\">245 (9.7%)</td>\n<td headers=\"stat_2_2\" class=\"gt_row gt_center\">73 (7.3%)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">318 (9.0%)</td>\n<td headers=\"p.value_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    1999</td>\n<td headers=\"stat_1_1\" class=\"gt_row gt_center\">139 (4.4%)</td>\n<td headers=\"stat_2_1\" class=\"gt_row gt_center\">38 (3.3%)</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">177 (4.1%)</td>\n<td headers=\"p.value_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_1_2\" class=\"gt_row gt_center\">144 (5.7%)</td>\n<td headers=\"stat_2_2\" class=\"gt_row gt_center\">29 (2.9%)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">173 (4.9%)</td>\n<td headers=\"p.value_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    2000</td>\n<td headers=\"stat_1_1\" class=\"gt_row gt_center\">100 (3.1%)</td>\n<td headers=\"stat_2_1\" class=\"gt_row gt_center\">21 (1.8%)</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">121 (2.8%)</td>\n<td headers=\"p.value_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_1_2\" class=\"gt_row gt_center\">93 (3.7%)</td>\n<td headers=\"stat_2_2\" class=\"gt_row gt_center\">31 (3.1%)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">124 (3.5%)</td>\n<td headers=\"p.value_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    2001</td>\n<td headers=\"stat_1_1\" class=\"gt_row gt_center\">66 (2.1%)</td>\n<td headers=\"stat_2_1\" class=\"gt_row gt_center\">21 (1.8%)</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">87 (2.0%)</td>\n<td headers=\"p.value_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_1_2\" class=\"gt_row gt_center\">71 (2.8%)</td>\n<td headers=\"stat_2_2\" class=\"gt_row gt_center\">17 (1.7%)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">88 (2.5%)</td>\n<td headers=\"p.value_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    2002</td>\n<td headers=\"stat_1_1\" class=\"gt_row gt_center\">23 (0.7%)</td>\n<td headers=\"stat_2_1\" class=\"gt_row gt_center\">0 (0%)</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">23 (0.5%)</td>\n<td headers=\"p.value_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_1_2\" class=\"gt_row gt_center\">24 (1.0%)</td>\n<td headers=\"stat_2_2\" class=\"gt_row gt_center\">1 (&lt;0.1%)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">25 (0.7%)</td>\n<td headers=\"p.value_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    2003</td>\n<td headers=\"stat_1_1\" class=\"gt_row gt_center\">106 (3.3%)</td>\n<td headers=\"stat_2_1\" class=\"gt_row gt_center\">4 (0.3%)</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">110 (2.5%)</td>\n<td headers=\"p.value_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_1_2\" class=\"gt_row gt_center\">105 (4.2%)</td>\n<td headers=\"stat_2_2\" class=\"gt_row gt_center\">7 (0.7%)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">112 (3.2%)</td>\n<td headers=\"p.value_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-style: italic;\">kappa</td>\n<td headers=\"stat_1_1\" class=\"gt_row gt_center\">1.15 (0.87, 1.50)</td>\n<td headers=\"stat_2_1\" class=\"gt_row gt_center\">1.51 (1.12, 2.05)</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">1.22 (0.92, 1.64)</td>\n<td headers=\"p.value_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_1_2\" class=\"gt_row gt_center\">1.24 (0.96, 1.58)</td>\n<td headers=\"stat_2_2\" class=\"gt_row gt_center\">1.65 (1.21, 2.24)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">1.33 (1.01, 1.75)</td>\n<td headers=\"p.value_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-style: italic;\">lambda</td>\n<td headers=\"stat_1_1\" class=\"gt_row gt_center\">1.4 (1.1, 1.8)</td>\n<td headers=\"stat_2_1\" class=\"gt_row gt_center\">1.7 (1.3, 2.3)</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">1.5 (1.2, 1.9)</td>\n<td headers=\"p.value_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_1_2\" class=\"gt_row gt_center\">1.5 (1.2, 1.8)</td>\n<td headers=\"stat_2_2\" class=\"gt_row gt_center\">1.9 (1.4, 2.5)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">1.6 (1.2, 2.0)</td>\n<td headers=\"p.value_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-style: italic;\">flc.grp</td>\n<td headers=\"stat_1_1\" class=\"gt_row gt_center\">5.00 (2.00, 7.00)</td>\n<td headers=\"stat_2_1\" class=\"gt_row gt_center\">7.00 (4.00, 9.00)</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">5.00 (3.00, 8.00)</td>\n<td headers=\"p.value_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_1_2\" class=\"gt_row gt_center\">5.00 (3.00, 7.00)</td>\n<td headers=\"stat_2_2\" class=\"gt_row gt_center\">8.00 (5.00, 10.00)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">6.00 (3.00, 8.00)</td>\n<td headers=\"p.value_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-style: italic;\">creatinine</td>\n<td headers=\"stat_1_1\" class=\"gt_row gt_center\">0.90 (0.80, 1.00)</td>\n<td headers=\"stat_2_1\" class=\"gt_row gt_center\">1.00 (0.90, 1.15)</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">0.90 (0.90, 1.10)</td>\n<td headers=\"p.value_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_1_2\" class=\"gt_row gt_center\">1.10 (1.00, 1.30)</td>\n<td headers=\"stat_2_2\" class=\"gt_row gt_center\">1.20 (1.00, 1.40)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">1.20 (1.00, 1.30)</td>\n<td headers=\"p.value_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Unknown</td>\n<td headers=\"stat_1_1\" class=\"gt_row gt_center\">665</td>\n<td headers=\"stat_2_1\" class=\"gt_row gt_center\">93</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">758</td>\n<td headers=\"p.value_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_1_2\" class=\"gt_row gt_center\">478</td>\n<td headers=\"stat_2_2\" class=\"gt_row gt_center\">114</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">592</td>\n<td headers=\"p.value_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-style: italic;\">mgus</td>\n<td headers=\"stat_1_1\" class=\"gt_row gt_center\">57 (1.8%)</td>\n<td headers=\"stat_2_1\" class=\"gt_row gt_center\">11 (0.9%)</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">68 (1.6%)</td>\n<td headers=\"p.value_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_1_2\" class=\"gt_row gt_center\">42 (1.7%)</td>\n<td headers=\"stat_2_2\" class=\"gt_row gt_center\">5 (0.5%)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">47 (1.3%)</td>\n<td headers=\"p.value_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-style: italic;\">futime</td>\n<td headers=\"stat_1_1\" class=\"gt_row gt_center\">4,638 (4,082, 4,862)</td>\n<td headers=\"stat_2_1\" class=\"gt_row gt_center\">2,184 (971, 3,231)</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">4,359 (2,870, 4,788)</td>\n<td headers=\"p.value_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_1_2\" class=\"gt_row gt_center\">4,578 (3,954, 4,844)</td>\n<td headers=\"stat_2_2\" class=\"gt_row gt_center\">2,159 (921, 3,338)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">4,226 (2,819, 4,740)</td>\n<td headers=\"p.value_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-style: italic;\">chapter</td>\n<td headers=\"stat_1_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_1_2\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2_2\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Blood</td>\n<td headers=\"stat_1_1\" class=\"gt_row gt_center\">0 (NA%)</td>\n<td headers=\"stat_2_1\" class=\"gt_row gt_center\">1 (&lt;0.1%)</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">1 (&lt;0.1%)</td>\n<td headers=\"p.value_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_1_2\" class=\"gt_row gt_center\">0 (NA%)</td>\n<td headers=\"stat_2_2\" class=\"gt_row gt_center\">3 (0.3%)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">3 (0.3%)</td>\n<td headers=\"p.value_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Circulatory</td>\n<td headers=\"stat_1_1\" class=\"gt_row gt_center\">0 (NA%)</td>\n<td headers=\"stat_2_1\" class=\"gt_row gt_center\">401 (34%)</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">401 (34%)</td>\n<td headers=\"p.value_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_1_2\" class=\"gt_row gt_center\">0 (NA%)</td>\n<td headers=\"stat_2_2\" class=\"gt_row gt_center\">344 (34%)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">344 (34%)</td>\n<td headers=\"p.value_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Congenital</td>\n<td headers=\"stat_1_1\" class=\"gt_row gt_center\">0 (NA%)</td>\n<td headers=\"stat_2_1\" class=\"gt_row gt_center\">0 (0%)</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">0 (0%)</td>\n<td headers=\"p.value_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_1_2\" class=\"gt_row gt_center\">0 (NA%)</td>\n<td headers=\"stat_2_2\" class=\"gt_row gt_center\">3 (0.3%)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">3 (0.3%)</td>\n<td headers=\"p.value_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Digestive</td>\n<td headers=\"stat_1_1\" class=\"gt_row gt_center\">0 (NA%)</td>\n<td headers=\"stat_2_1\" class=\"gt_row gt_center\">37 (3.2%)</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">37 (3.2%)</td>\n<td headers=\"p.value_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_1_2\" class=\"gt_row gt_center\">0 (NA%)</td>\n<td headers=\"stat_2_2\" class=\"gt_row gt_center\">29 (2.9%)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">29 (2.9%)</td>\n<td headers=\"p.value_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Endocrine</td>\n<td headers=\"stat_1_1\" class=\"gt_row gt_center\">0 (NA%)</td>\n<td headers=\"stat_2_1\" class=\"gt_row gt_center\">25 (2.1%)</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">25 (2.1%)</td>\n<td headers=\"p.value_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_1_2\" class=\"gt_row gt_center\">0 (NA%)</td>\n<td headers=\"stat_2_2\" class=\"gt_row gt_center\">23 (2.3%)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">23 (2.3%)</td>\n<td headers=\"p.value_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    External Causes</td>\n<td headers=\"stat_1_1\" class=\"gt_row gt_center\">0 (NA%)</td>\n<td headers=\"stat_2_1\" class=\"gt_row gt_center\">35 (3.0%)</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">35 (3.0%)</td>\n<td headers=\"p.value_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_1_2\" class=\"gt_row gt_center\">0 (NA%)</td>\n<td headers=\"stat_2_2\" class=\"gt_row gt_center\">31 (3.1%)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">31 (3.1%)</td>\n<td headers=\"p.value_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Genitourinary</td>\n<td headers=\"stat_1_1\" class=\"gt_row gt_center\">0 (NA%)</td>\n<td headers=\"stat_2_1\" class=\"gt_row gt_center\">20 (1.7%)</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">20 (1.7%)</td>\n<td headers=\"p.value_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_1_2\" class=\"gt_row gt_center\">0 (NA%)</td>\n<td headers=\"stat_2_2\" class=\"gt_row gt_center\">22 (2.2%)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">22 (2.2%)</td>\n<td headers=\"p.value_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Ill Defined</td>\n<td headers=\"stat_1_1\" class=\"gt_row gt_center\">0 (NA%)</td>\n<td headers=\"stat_2_1\" class=\"gt_row gt_center\">25 (2.1%)</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">25 (2.1%)</td>\n<td headers=\"p.value_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_1_2\" class=\"gt_row gt_center\">0 (NA%)</td>\n<td headers=\"stat_2_2\" class=\"gt_row gt_center\">13 (1.3%)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">13 (1.3%)</td>\n<td headers=\"p.value_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Infectious</td>\n<td headers=\"stat_1_1\" class=\"gt_row gt_center\">0 (NA%)</td>\n<td headers=\"stat_2_1\" class=\"gt_row gt_center\">23 (2.0%)</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">23 (2.0%)</td>\n<td headers=\"p.value_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_1_2\" class=\"gt_row gt_center\">0 (NA%)</td>\n<td headers=\"stat_2_2\" class=\"gt_row gt_center\">9 (0.9%)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">9 (0.9%)</td>\n<td headers=\"p.value_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Injury and Poisoning</td>\n<td headers=\"stat_1_1\" class=\"gt_row gt_center\">0 (NA%)</td>\n<td headers=\"stat_2_1\" class=\"gt_row gt_center\">12 (1.0%)</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">12 (1.0%)</td>\n<td headers=\"p.value_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_1_2\" class=\"gt_row gt_center\">0 (NA%)</td>\n<td headers=\"stat_2_2\" class=\"gt_row gt_center\">9 (0.9%)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">9 (0.9%)</td>\n<td headers=\"p.value_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Mental</td>\n<td headers=\"stat_1_1\" class=\"gt_row gt_center\">0 (NA%)</td>\n<td headers=\"stat_2_1\" class=\"gt_row gt_center\">100 (8.6%)</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">100 (8.6%)</td>\n<td headers=\"p.value_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_1_2\" class=\"gt_row gt_center\">0 (NA%)</td>\n<td headers=\"stat_2_2\" class=\"gt_row gt_center\">44 (4.4%)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">44 (4.4%)</td>\n<td headers=\"p.value_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Musculoskeletal</td>\n<td headers=\"stat_1_1\" class=\"gt_row gt_center\">0 (NA%)</td>\n<td headers=\"stat_2_1\" class=\"gt_row gt_center\">11 (0.9%)</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">11 (0.9%)</td>\n<td headers=\"p.value_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_1_2\" class=\"gt_row gt_center\">0 (NA%)</td>\n<td headers=\"stat_2_2\" class=\"gt_row gt_center\">3 (0.3%)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">3 (0.3%)</td>\n<td headers=\"p.value_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Neoplasms</td>\n<td headers=\"stat_1_1\" class=\"gt_row gt_center\">0 (NA%)</td>\n<td headers=\"stat_2_1\" class=\"gt_row gt_center\">279 (24%)</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">279 (24%)</td>\n<td headers=\"p.value_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_1_2\" class=\"gt_row gt_center\">0 (NA%)</td>\n<td headers=\"stat_2_2\" class=\"gt_row gt_center\">288 (29%)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">288 (29%)</td>\n<td headers=\"p.value_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Nervous</td>\n<td headers=\"stat_1_1\" class=\"gt_row gt_center\">0 (NA%)</td>\n<td headers=\"stat_2_1\" class=\"gt_row gt_center\">73 (6.3%)</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">73 (6.3%)</td>\n<td headers=\"p.value_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_1_2\" class=\"gt_row gt_center\">0 (NA%)</td>\n<td headers=\"stat_2_2\" class=\"gt_row gt_center\">57 (5.7%)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">57 (5.7%)</td>\n<td headers=\"p.value_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Respiratory</td>\n<td headers=\"stat_1_1\" class=\"gt_row gt_center\">0 (NA%)</td>\n<td headers=\"stat_2_1\" class=\"gt_row gt_center\">121 (10%)</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">121 (10%)</td>\n<td headers=\"p.value_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_1_2\" class=\"gt_row gt_center\">0 (NA%)</td>\n<td headers=\"stat_2_2\" class=\"gt_row gt_center\">124 (12%)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">124 (12%)</td>\n<td headers=\"p.value_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Skin</td>\n<td headers=\"stat_1_1\" class=\"gt_row gt_center\">0 (NA%)</td>\n<td headers=\"stat_2_1\" class=\"gt_row gt_center\">2 (0.2%)</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">2 (0.2%)</td>\n<td headers=\"p.value_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_1_2\" class=\"gt_row gt_center\">0 (NA%)</td>\n<td headers=\"stat_2_2\" class=\"gt_row gt_center\">2 (0.2%)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">2 (0.2%)</td>\n<td headers=\"p.value_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Unknown</td>\n<td headers=\"stat_1_1\" class=\"gt_row gt_center\">3,185</td>\n<td headers=\"stat_2_1\" class=\"gt_row gt_center\">0</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">3,185</td>\n<td headers=\"p.value_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_1_2\" class=\"gt_row gt_center\">2,520</td>\n<td headers=\"stat_2_2\" class=\"gt_row gt_center\">0</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">2,520</td>\n<td headers=\"p.value_2\" class=\"gt_row gt_center\"><br /></td></tr>\n  </tbody>\n  \n  <tfoot class=\"gt_footnotes\">\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"9\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height: 0;\"><sup>1</sup></span> <div data-qmd-base64=\"TWVkaWFuIChRMSwgUTMpOyBuICglKQ==\"><div class='gt_from_md'><p>Median (Q1, Q3); n (%)</p>\n</div></div></td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\n### Comments (pros/cons)\n\n-   **Pros**\n    -   Massive amount of options/variability in output\n    -   Formatting is very nice in html form.\n    -   Easy to add in and specify arguments to testing.\n-   **Cons**\n    -   Does not render in Word document markdown format (can save output to Word document).\n    -   Can be a bit clumsy when specifying some arguments (must be inside list, etc.)\n    -   Can be annoying when working with high dimensional data (selecting large number of columns).\n    -   When applying multiple tests within a class of variables (e.g., t-test for one continuous variable, Kruskal-Wallis test for another) it is not obvious which test is applied to which. Only the p-value is returned in each instance.\n\n<br>\n\n## Method 4 - `tableone`\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntableone::CreateTableOne(data = flchain,\n                         strata = \"death\",\n                         test = TRUE,\n                         testApprox = chisq.test, # For categorical variables (where Chi-Square approximation is appropriate), apply chi-square test\n                         argsApprox = list(correct = T), # Arguments to above\n                         \n                         testExact = fisher.test, # For categorical variables with small counts, apply Fisher's test\n                         argsExact = list(workspace = 2*10^5), # Arguments to above\n                         \n                         testNormal = oneway.test, # For normally distributed continuous variables, apply one-way test (==t.test if 2 groups)\n                         argsNormal = list(var.equal = T), # Arguments to above\n                         \n                         testNonNormal = kruskal.test, # For non-normally distributed continuous variables, apply Kruskal-Wallis rank-sum test\n                         argsNonNormal = list(NULL), # Arguments to above\n                         \n                         addOverall = T # Add overall column\n                         )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                         Stratified by death\n                          Overall           0                1                \n  n                          7874              5705             2169          \n  age (mean (SD))           64.29 (10.46)     60.84 (8.20)     73.39 (10.32)  \n  sex = M (%)                3524 (44.8)       2520 (44.2)      1004 (46.3)   \n  sample.yr (mean (SD))   1996.79 (1.77)    1996.92 (1.88)   1996.44 (1.35)   \n  kappa (mean (SD))          1.43 (0.90)       1.27 (0.65)      1.85 (1.26)   \n  lambda (mean (SD))         1.70 (1.03)       1.54 (0.70)      2.13 (1.52)   \n  flc.grp (mean (SD))        5.47 (2.86)       4.98 (2.72)      6.77 (2.84)   \n  creatinine (mean (SD))     1.09 (0.42)       1.05 (0.31)      1.19 (0.59)   \n  mgus (mean (SD))           0.01 (0.12)       0.02 (0.13)      0.01 (0.09)   \n  futime (mean (SD))      3661.04 (1432.68) 4226.20 (974.25) 2174.54 (1380.34)\n  death (mean (SD))          0.28 (0.45)       0.00 (0.00)      1.00 (0.00)   \n  chapter (%)                                                                 \n     Blood                      4 ( 0.2)          0 ( NaN)         4 ( 0.2)   \n     Circulatory              745 (34.3)          0 ( NaN)       745 (34.3)   \n     Congenital                 3 ( 0.1)          0 ( NaN)         3 ( 0.1)   \n     Digestive                 66 ( 3.0)          0 ( NaN)        66 ( 3.0)   \n     Endocrine                 48 ( 2.2)          0 ( NaN)        48 ( 2.2)   \n     External Causes           66 ( 3.0)          0 ( NaN)        66 ( 3.0)   \n     Genitourinary             42 ( 1.9)          0 ( NaN)        42 ( 1.9)   \n     Ill Defined               38 ( 1.8)          0 ( NaN)        38 ( 1.8)   \n     Infectious                32 ( 1.5)          0 ( NaN)        32 ( 1.5)   \n     Injury and Poisoning      21 ( 1.0)          0 ( NaN)        21 ( 1.0)   \n     Mental                   144 ( 6.6)          0 ( NaN)       144 ( 6.6)   \n     Musculoskeletal           14 ( 0.6)          0 ( NaN)        14 ( 0.6)   \n     Neoplasms                567 (26.1)          0 ( NaN)       567 (26.1)   \n     Nervous                  130 ( 6.0)          0 ( NaN)       130 ( 6.0)   \n     Respiratory              245 (11.3)          0 ( NaN)       245 (11.3)   \n     Skin                       4 ( 0.2)          0 ( NaN)         4 ( 0.2)   \n                         Stratified by death\n                          p      test\n  n                                  \n  age (mean (SD))         <0.001     \n  sex = M (%)              NA        \n  sample.yr (mean (SD))   <0.001     \n  kappa (mean (SD))       <0.001     \n  lambda (mean (SD))      <0.001     \n  flc.grp (mean (SD))     <0.001     \n  creatinine (mean (SD))  <0.001     \n  mgus (mean (SD))         0.001     \n  futime (mean (SD))      <0.001     \n  death (mean (SD))       <0.001     \n  chapter (%)              NA        \n     Blood                           \n     Circulatory                     \n     Congenital                      \n     Digestive                       \n     Endocrine                       \n     External Causes                 \n     Genitourinary                   \n     Ill Defined                     \n     Infectious                      \n     Injury and Poisoning            \n     Mental                          \n     Musculoskeletal                 \n     Neoplasms                       \n     Nervous                         \n     Respiratory                     \n     Skin                            \n```\n\n\n:::\n:::\n\n\n### Comments (pros/cons)\n\n-   **Pros**\n    -   Implicitly tests each variable for appropriateness of test (e.g., normal vs. non-normal etc.)\n    -   Seems like a good \"first pass\" sort of function to apply in cases where we have a lot of variables. Perhaps less so a \"publication ready\" function.\n-   **Cons**\n    -   Renders nicely to console, not so much to Rmarkdown (relative to above)\n    -   Clunky to specify testing\n        -   Cannot easily tell which test is being applied to which variable (cannot tell whether variable is \"normal\" vs. \"non-normal\")\n        -   Different arguments specified for approximate vs. exact categorical tests (chi-square vs. Fisher's test) and normal vs. non-normal continuous tests (t-test vs. Kruskal-Wallis Rank-Sum test)\n    -   Output is clunky and cannot be tweaked (decimal places, structure of output)\n\n<br>\n\n## Method 5 - `desctable`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nflchain %>% \n  group_by(death) %>%\n  desctable::desc_table(\"N\"    = length,\n                        \"Min\"  = min,\n                        \"Q1\"   = ~quantile(., .25),\n                        \"Med\"  = median,\n                        \"Mean\" = mean,\n                        \"Q3\"   = ~quantile(., .75),\n                        \"Max\"  = max,\n                        \"sd\"   = sd,\n                        \"IQR\"  = IQR) %>%\n  #desctable::desc_tests() %>%\n  desctable::desc_output(\"DT\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-a2197936f7474b316cd3\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-a2197936f7474b316cd3\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"class\":\"display\",\"extensions\":[\"FixedHeader\",\"FixedColumns\",\"Buttons\"],\"data\":[[\"age\",\"<b>sex<\\/b>\",\"&nbsp;&nbsp;&nbsp;&nbsp;F\",\"&nbsp;&nbsp;&nbsp;&nbsp;M\",\"sample.yr\",\"kappa\",\"lambda\",\"flc.grp\",\"creatinine\",\"mgus\",\"futime\",\"<b>chapter<\\/b>\",\"&nbsp;&nbsp;&nbsp;&nbsp;Blood\",\"&nbsp;&nbsp;&nbsp;&nbsp;Circulatory\",\"&nbsp;&nbsp;&nbsp;&nbsp;Congenital\",\"&nbsp;&nbsp;&nbsp;&nbsp;Digestive\",\"&nbsp;&nbsp;&nbsp;&nbsp;Endocrine\",\"&nbsp;&nbsp;&nbsp;&nbsp;External Causes\",\"&nbsp;&nbsp;&nbsp;&nbsp;Genitourinary\",\"&nbsp;&nbsp;&nbsp;&nbsp;Ill Defined\",\"&nbsp;&nbsp;&nbsp;&nbsp;Infectious\",\"&nbsp;&nbsp;&nbsp;&nbsp;Injury and Poisoning\",\"&nbsp;&nbsp;&nbsp;&nbsp;Mental\",\"&nbsp;&nbsp;&nbsp;&nbsp;Musculoskeletal\",\"&nbsp;&nbsp;&nbsp;&nbsp;Neoplasms\",\"&nbsp;&nbsp;&nbsp;&nbsp;Nervous\",\"&nbsp;&nbsp;&nbsp;&nbsp;Respiratory\",\"&nbsp;&nbsp;&nbsp;&nbsp;Skin\"],[2169,2169,1165,1004,2169,2169,2169,2169,1962,2169,2169,2169,4,745,3,66,48,66,42,38,32,21,144,14,567,130,245,4],[50,null,null,null,1995,0.118,0.047,1,0.4,0,0,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],[67,null,null,null,1996,1.16,1.38,5,0.9,0,945,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],[74,null,null,null,1996,1.57,1.77,7,1.1,0,2165,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],[73.3863531581374,null,null,null,1996.44213923467,1.84505071461503,2.13217956690648,6.767173812816966,1.193272171253823,0.007376671277086215,2174.536191793453,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],[81,null,null,null,1997,2.14,2.38,9,1.3,0,3282,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],[101,null,null,null,2003,16.4,26.6,10,10,1,4998,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],[10.32114039915452,null,null,null,1.352015796164042,1.259979923261056,1.52214976554882,2.836847587063684,0.5885319087169761,0.08558991425576572,1380.340054065129,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],[14,null,null,null,1,0.9800000000000002,1,4,0.4,0,2337,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],[5705,5705,3185,2520,5705,5705,5705,5705,4562,5705,5705,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[50,null,null,null,1995,0.01,0.04,1,0.5,0,1,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],[54,null,null,null,1996,0.91,1.16,3,0.9,0,4033,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],[59,null,null,null,1996,1.19,1.43,5,1,0,4607,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],[60.83593339176161,null,null,null,1996.923400525855,1.27341703768624,1.539309956178791,4.977563540753724,1.050613765892153,0.01735319894829097,4226.201226993865,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],[66,null,null,null,1997,1.53,1.78,7,1.2,0,4852,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],[93,null,null,null,2003,20.5,17.9,10,10.8,1,5215,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],[8.198134105675322,null,null,null,1.882018236354332,0.6454306412209738,0.6992317288622574,2.715247326818556,0.3050561575408096,0.1305950034537678,974.2495638471071,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],[12,null,null,null,1,0.62,0.6200000000000001,4,0.2999999999999999,0,819,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th rowspan=\\\"2\\\"><\\/th>\\n      <th colspan=\\\"9\\\">death = 1 (N = 2169)<\\/th>\\n      <th colspan=\\\"9\\\">death = 0 (N = 5705)<\\/th>\\n    <\\/tr>\\n    <tr>\\n      <th>N<\\/th>\\n      <th>Min<\\/th>\\n      <th>Q1<\\/th>\\n      <th>Med<\\/th>\\n      <th>Mean<\\/th>\\n      <th>Q3<\\/th>\\n      <th>Max<\\/th>\\n      <th>sd<\\/th>\\n      <th>IQR<\\/th>\\n      <th>N<\\/th>\\n      <th>Min<\\/th>\\n      <th>Q1<\\/th>\\n      <th>Med<\\/th>\\n      <th>Mean<\\/th>\\n      <th>Q3<\\/th>\\n      <th>Max<\\/th>\\n      <th>sd<\\/th>\\n      <th>IQR<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"paging\":false,\"info\":false,\"search\":[],\"dom\":\"Brtip\",\"fixedColumns\":true,\"fixedHeader\":true,\"buttons\":[\"copy\",\"excel\"],\"columnDefs\":[{\"targets\":2,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 2, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":3,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 2, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":4,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 2, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":5,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 2, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":6,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 2, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":7,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 2, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":8,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 2, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":9,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 2, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":11,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 2, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":12,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 2, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":13,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 2, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":14,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 2, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":15,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 2, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":16,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 2, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":17,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 2, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":18,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 2, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"className\":\"dt-right\",\"targets\":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18]},{\"orderable\":false,\"targets\":0},{\"name\":\" \",\"targets\":0},{\"name\":\"N\",\"targets\":1},{\"name\":\"Min\",\"targets\":2},{\"name\":\"Q1\",\"targets\":3},{\"name\":\"Med\",\"targets\":4},{\"name\":\"Mean\",\"targets\":5},{\"name\":\"Q3\",\"targets\":6},{\"name\":\"Max\",\"targets\":7},{\"name\":\"sd\",\"targets\":8},{\"name\":\"IQR\",\"targets\":9},{\"name\":\"N\",\"targets\":10},{\"name\":\"Min\",\"targets\":11},{\"name\":\"Q1\",\"targets\":12},{\"name\":\"Med\",\"targets\":13},{\"name\":\"Mean\",\"targets\":14},{\"name\":\"Q3\",\"targets\":15},{\"name\":\"Max\",\"targets\":16},{\"name\":\"sd\",\"targets\":17},{\"name\":\"IQR\",\"targets\":18}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false}},\"evals\":[\"options.columnDefs.0.render\",\"options.columnDefs.1.render\",\"options.columnDefs.2.render\",\"options.columnDefs.3.render\",\"options.columnDefs.4.render\",\"options.columnDefs.5.render\",\"options.columnDefs.6.render\",\"options.columnDefs.7.render\",\"options.columnDefs.8.render\",\"options.columnDefs.9.render\",\"options.columnDefs.10.render\",\"options.columnDefs.11.render\",\"options.columnDefs.12.render\",\"options.columnDefs.13.render\",\"options.columnDefs.14.render\",\"options.columnDefs.15.render\"],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n### Comments (pros/cons)\n\n-   **Pros**\n    -   Interactive table\n    -   Can copy output directly to clipboard, excel (with interactive button)\n-   **Cons**\n    -   Must specify grouping variables outside of the `desctable` environment\n    -   Is slooow.\n    -   Specification of tests are a little clunky and troublesome with categorical factors.\n    -   Specification of statistics between categorical and continuous variables are a little clunky (shows IQR for categorical variables, etc.)\n\n<br>\n\n<br>\n\n## Method 6 - `summarytools`\n\n\n\n```{.r .cell-code}\nflchain %>%\n  group_by(death) %>%\n  summarytools::dfSummary(round.digits = 2) %>%\n  base::print(.)\n```\n\nData Frame Summary  \nflchain  \nGroup: death = 0  \nDimensions: 5705 x 11  \nDuplicates: 0  \n\n------------------------------------------------------------------------------------------------------------------\nNo   Variable     Stats / Values                Freqs (% of Valid)     Graph                 Valid      Missing   \n---- ------------ ----------------------------- ---------------------- --------------------- ---------- ----------\n1    age          Mean (sd) : 60.84 (8.2)       44 distinct values     :                     5705       0         \n     [numeric]    min < med < max:                                     : .                   (100.0%)   (0.0%)    \n                  50 < 59 < 93                                         : : .                                      \n                  IQR (CV) : 12 (0.13)                                 : : : : .                                  \n                                                                       : : : : : .                                \n\n2    sex          1. F                          3185 (55.8%)           IIIIIIIIIII           5705       0         \n     [factor]     2. M                          2520 (44.2%)           IIIIIIII              (100.0%)   (0.0%)    \n\n3    sample.yr    Mean (sd) : 1996.92 (1.88)    1995 :  861 (15.1%)    III                   5705       0         \n     [numeric]    min < med < max:              1996 : 2435 (42.7%)    IIIIIIII              (100.0%)   (0.0%)    \n                  1995 < 1996 < 2003            1997 : 1012 (17.7%)    III                                        \n                  IQR (CV) : 1 (0)              1998 :  526 ( 9.2%)    I                                          \n                                                1999 :  283 ( 5.0%)                                               \n                                                2000 :  193 ( 3.4%)                                               \n                                                2001 :  137 ( 2.4%)                                               \n                                                2002 :   47 ( 0.8%)                                               \n                                                2003 :  211 ( 3.7%)                                               \n\n4    kappa        Mean (sd) : 1.27 (0.65)       765 distinct values    :                     5705       0         \n     [numeric]    min < med < max:                                     :                     (100.0%)   (0.0%)    \n                  0.01 < 1.19 < 20.5                                   :                                          \n                  IQR (CV) : 0.62 (0.51)                               :                                          \n                                                                       : .                                        \n\n5    lambda       Mean (sd) : 1.54 (0.7)        626 distinct values    :                     5705       0         \n     [numeric]    min < med < max:                                     :                     (100.0%)   (0.0%)    \n                  0.04 < 1.43 < 17.9                                   :                                          \n                  IQR (CV) : 0.62 (0.45)                               : .                                        \n                                                                       : :                                        \n\n6    flc.grp      Mean (sd) : 4.98 (2.72)       1 : 654 (11.5%)        II                    5705       0         \n     [numeric]    min < med < max:              2 : 690 (12.1%)        II                    (100.0%)   (0.0%)    \n                  1 < 5 < 10                    3 : 678 (11.9%)        II                                         \n                  IQR (CV) : 4 (0.55)           4 : 630 (11.0%)        II                                         \n                                                5 : 637 (11.2%)        II                                         \n                                                6 : 581 (10.2%)        II                                         \n                                                7 : 588 (10.3%)        II                                         \n                                                8 : 482 ( 8.4%)        I                                          \n                                                9 : 484 ( 8.5%)        I                                          \n                                                10 : 281 ( 4.9%)                                                  \n\n7    creatinine   Mean (sd) : 1.05 (0.31)       27 distinct values     :                     4562       1143      \n     [numeric]    min < med < max:                                     :                     (80.0%)    (20.0%)   \n                  0.5 < 1 < 10.8                                       :                                          \n                  IQR (CV) : 0.3 (0.29)                                :                                          \n                                                                       :                                          \n\n8    mgus         Min  : 0                      0 : 5606 (98.3%)       IIIIIIIIIIIIIIIIIII   5705       0         \n     [numeric]    Mean : 0.02                   1 :   99 ( 1.7%)                             (100.0%)   (0.0%)    \n                  Max  : 1                                                                                        \n\n9    futime       Mean (sd) : 4226.2 (974.25)   1740 distinct values                     :   5705       0         \n     [integer]    min < med < max:                                                     . :   (100.0%)   (0.0%)    \n                  1 < 4607 < 5215                                                      : :                        \n                  IQR (CV) : 819 (0.23)                                              . : :                        \n                                                                               . . . : : :                        \n\n11   chapter      1. Blood                      All NA's                                     0          5705      \n     [factor]     2. Circulatory                                                             (0.0%)     (100.0%)  \n                  3. Congenital                                                                                   \n                  4. Digestive                                                                                    \n                  5. Endocrine                                                                                    \n                  6. External Causes                                                                              \n                  7. Genitourinary                                                                                \n                  8. Ill Defined                                                                                  \n                  9. Infectious                                                                                   \n                  10. Injury and Poisoning                                                                        \n                  11. Mental                                                                                      \n                  12. Musculoskeletal                                                                             \n                  13. Neoplasms                                                                                   \n                  14. Nervous                                                                                     \n                  15. Respiratory                                                                                 \n                  16. Skin                                                                                        \n------------------------------------------------------------------------------------------------------------------\n\nGroup: death = 1  \nDimensions: 2169 x 11  \nDuplicates: 0  \n\n-------------------------------------------------------------------------------------------------------------------\nNo   Variable     Stats / Values                  Freqs (% of Valid)     Graph                 Valid      Missing  \n---- ------------ ------------------------------- ---------------------- --------------------- ---------- ---------\n1    age          Mean (sd) : 73.39 (10.32)       51 distinct values             . :           2169       0        \n     [numeric]    min < med < max:                                             : : : :         (100.0%)   (0.0%)   \n                  50 < 74 < 101                                              . : : : :                             \n                  IQR (CV) : 14 (0.14)                                   . : : : : : : :                           \n                                                                         : : : : : : : : .                         \n\n2    sex          1. F                            1165 (53.7%)           IIIIIIIIII            2169       0        \n     [factor]     2. M                            1004 (46.3%)           IIIIIIIII             (100.0%)   (0.0%)   \n\n3    sample.yr    Mean (sd) : 1996.44 (1.35)      1995 :  414 (19.1%)    III                   2169       0        \n     [numeric]    min < med < max:                1996 : 1056 (48.7%)    IIIIIIIII             (100.0%)   (0.0%)   \n                  1995 < 1996 < 2003              1997 :  369 (17.0%)    III                                       \n                  IQR (CV) : 1 (0)                1998 :  161 ( 7.4%)    I                                         \n                                                  1999 :   67 ( 3.1%)                                              \n                                                  2000 :   52 ( 2.4%)                                              \n                                                  2001 :   38 ( 1.8%)                                              \n                                                  2002 :    1 ( 0.0%)                                              \n                                                  2003 :   11 ( 0.5%)                                              \n\n4    kappa        Mean (sd) : 1.85 (1.26)         525 distinct values    :                     2169       0        \n     [numeric]    min < med < max:                                       :                     (100.0%)   (0.0%)   \n                  0.12 < 1.57 < 16.4                                     : :                                       \n                  IQR (CV) : 0.98 (0.68)                                 : :                                       \n                                                                         : : .                                     \n\n5    lambda       Mean (sd) : 2.13 (1.52)         479 distinct values    :                     2169       0        \n     [numeric]    min < med < max:                                       :                     (100.0%)   (0.0%)   \n                  0.05 < 1.77 < 26.6                                     :                                         \n                  IQR (CV) : 1 (0.71)                                    :                                         \n                                                                         : :                                       \n\n6    flc.grp      Mean (sd) : 6.77 (2.84)         1 : 115 ( 5.3%)        I                     2169       0        \n     [numeric]    min < med < max:                2 : 121 ( 5.6%)        I                     (100.0%)   (0.0%)   \n                  1 < 7 < 10                      3 : 142 ( 6.5%)        I                                         \n                  IQR (CV) : 4 (0.42)             4 : 156 ( 7.2%)        I                                         \n                                                  5 : 154 ( 7.1%)        I                                         \n                                                  6 : 210 ( 9.7%)        I                                         \n                                                  7 : 218 (10.1%)        II                                        \n                                                  8 : 248 (11.4%)        II                                        \n                                                  9 : 319 (14.7%)        II                                        \n                                                  10 : 486 (22.4%)       IIII                                      \n\n7    creatinine   Mean (sd) : 1.19 (0.59)         45 distinct values     :                     1962       207      \n     [numeric]    min < med < max:                                       :                     (90.5%)    (9.5%)   \n                  0.4 < 1.1 < 10                                         :                                         \n                  IQR (CV) : 0.4 (0.49)                                  :                                         \n                                                                         : :                                       \n\n8    mgus         Min  : 0                        0 : 2153 (99.3%)       IIIIIIIIIIIIIIIIIII   2169       0        \n     [numeric]    Mean : 0.01                     1 :   16 ( 0.7%)                             (100.0%)   (0.0%)   \n                  Max  : 1                                                                                         \n\n9    futime       Mean (sd) : 2174.54 (1380.34)   1738 distinct values   :                     2169       0        \n     [integer]    min < med < max:                                       : .   : . . .         (100.0%)   (0.0%)   \n                  0 < 2165 < 4998                                        : : : : : : : : :                         \n                  IQR (CV) : 2337 (0.63)                                 : : : : : : : : :                         \n                                                                         : : : : : : : : : :                       \n\n11   chapter      1. Blood                           4 ( 0.2%)                                 2169       0        \n     [factor]     2. Circulatory                   745 (34.3%)           IIIIII                (100.0%)   (0.0%)   \n                  3. Congenital                      3 ( 0.1%)                                                     \n                  4. Digestive                      66 ( 3.0%)                                                     \n                  5. Endocrine                      48 ( 2.2%)                                                     \n                  6. External Causes                66 ( 3.0%)                                                     \n                  7. Genitourinary                  42 ( 1.9%)                                                     \n                  8. Ill Defined                    38 ( 1.8%)                                                     \n                  9. Infectious                     32 ( 1.5%)                                                     \n                  10. Injury and Poisoning          21 ( 1.0%)                                                     \n                  [ 6 others ]                    1104 (50.9%)           IIIIIIIIII                                \n-------------------------------------------------------------------------------------------------------------------\n\n\n### Comments\n\n-   **Pros**\n    -   Has some pretty cool graphs\n-   **Cons**\n    -   A bit fiddly to render nicely in RMarkdown. Requires specification of additional arguments in chunk header (`results = asis`)\n    -   Stratification is clunky in output, and requires manual `group_by` argument.\n\n<br>\n\n## Acknowledgements\n\nThanks to Wesley Billingham, Matt Cooper, and Elizabeth McKinnon for providing feedback on and reviewing this post.\n\nYou can look forward to seeing posts from these other team members here in the coming weeks and months.\n\n<br>\n\n## Reproducibility Information\n\nTo access the .qmd (Quarto markdown) files as well as any R scripts or data that was used in this post, please visit our GitHub:\n\n<https://github.com/The-Kids-Biostats/The-Kids-Biostats.github.io/tree/main/posts/parallel>\n\nThe session information can also be seen below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsessionInfo()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR version 4.3.2 (2023-10-31 ucrt)\nPlatform: x86_64-w64-mingw32/x64 (64-bit)\nRunning under: Windows 10 x64 (build 19045)\n\nMatrix products: default\n\n\nlocale:\n[1] LC_COLLATE=English_Australia.utf8  LC_CTYPE=English_Australia.utf8   \n[3] LC_MONETARY=English_Australia.utf8 LC_NUMERIC=C                      \n[5] LC_TIME=English_Australia.utf8    \n\ntime zone: Australia/Perth\ntzcode source: internal\n\nattached base packages:\n[1] stats     graphics  grDevices utils     datasets  methods   base     \n\nother attached packages:\n [1] tableone_0.13.2    desctable_0.3.0    pander_0.6.5       summarytools_1.0.1\n [5] gtsummary_2.0.0    lubridate_1.9.3    forcats_1.0.0      stringr_1.5.1     \n [9] dplyr_1.1.4        purrr_1.0.2        readr_2.1.5        tidyr_1.3.1       \n[13] tibble_3.2.1       ggplot2_3.5.1      tidyverse_2.0.0   \n\nloaded via a namespace (and not attached):\n [1] gtable_0.3.5      xfun_0.45         htmlwidgets_1.6.4 lattice_0.22-6   \n [5] tzdb_0.4.0        crosstalk_1.2.1   vctrs_0.6.5       tools_4.3.2      \n [9] generics_0.1.3    proxy_0.4-27      fansi_1.0.6       pkgconfig_2.0.3  \n[13] Matrix_1.6-5      checkmate_2.3.2   pryr_0.1.6        gt_0.11.0        \n[17] lifecycle_1.0.4   compiler_4.3.2    rapportools_1.1   munsell_0.5.1    \n[21] mitools_2.4       codetools_0.2-20  survey_4.4-2      class_7.3-22     \n[25] sass_0.4.9        htmltools_0.5.8.1 yaml_2.3.10       jquerylib_0.1.4  \n[29] pillar_1.9.0      MASS_7.3-60.0.1   DT_0.33           magick_2.8.4     \n[33] commonmark_1.9.1  tidyselect_1.2.1  digest_0.6.36     stringi_1.8.4    \n[37] reshape2_1.4.4    splines_4.3.2     labelled_2.13.0   fastmap_1.2.0    \n[41] grid_4.3.2        colorspace_2.1-0  cli_3.6.3         magrittr_2.0.3   \n[45] cards_0.2.0       base64enc_0.1-3   survival_3.7-0    utf8_1.2.4       \n[49] e1071_1.7-14      withr_3.0.1       scales_1.3.0      backports_1.5.0  \n[53] timechange_0.3.0  rmarkdown_2.27    matrixStats_1.3.0 zoo_1.8-12       \n[57] hms_1.1.3         evaluate_0.24.0   haven_2.5.4       knitr_1.48       \n[61] tcltk_4.3.2       markdown_1.13     rlang_1.1.4       Rcpp_1.0.13      \n[65] DBI_1.2.3         glue_1.7.0        xml2_1.3.6        rstudioapi_0.16.0\n[69] jsonlite_1.8.8    R6_2.5.1          plyr_1.8.9       \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/htmltools-fill-0.5.8.1/fill.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\n<link href=\"../../site_libs/datatables-css-0.0.0/datatables-crosstalk.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/datatables-binding-0.33/datatables.js\"></script>\n<script src=\"../../site_libs/jquery-3.6.0/jquery-3.6.0.min.js\"></script>\n<link href=\"../../site_libs/dt-core-1.13.6/css/jquery.dataTables.min.css\" rel=\"stylesheet\" />\n<link href=\"../../site_libs/dt-core-1.13.6/css/jquery.dataTables.extra.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/dt-core-1.13.6/js/jquery.dataTables.min.js\"></script>\n<link href=\"../../site_libs/dt-ext-fixedheader-1.13.6/css/fixedHeader.dataTables.min.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/dt-ext-fixedheader-1.13.6/js/dataTables.fixedHeader.min.js\"></script>\n<link href=\"../../site_libs/dt-ext-fixedcolumns-1.13.6/css/fixedColumns.dataTables.min.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/dt-ext-fixedcolumns-1.13.6/js/dataTables.fixedColumns.min.js\"></script>\n<script src=\"../../site_libs/jszip-1.13.6/jszip.min.js\"></script>\n<link href=\"../../site_libs/dt-ext-buttons-1.13.6/css/buttons.dataTables.min.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/dt-ext-buttons-1.13.6/js/dataTables.buttons.min.js\"></script>\n<script src=\"../../site_libs/dt-ext-buttons-1.13.6/js/buttons.html5.min.js\"></script>\n<script src=\"../../site_libs/dt-ext-buttons-1.13.6/js/buttons.colVis.min.js\"></script>\n<script src=\"../../site_libs/dt-ext-buttons-1.13.6/js/buttons.print.min.js\"></script>\n<link href=\"../../site_libs/crosstalk-1.2.1/css/crosstalk.min.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/crosstalk-1.2.1/js/crosstalk.min.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}